### ISSUE TITLE
swift-parsing 0.12.0 (Swift 5.8 Support) has breaking change for <= 5.7

### ISSUE THREAD

**Issue by drewmclean** [JaapWijnen/swift-xml-parser#3]
Hello, 

It appears that pointfree has release a [newer version](https://github.com/pointfreeco/swift-parsing/releases) of `swift-parsing` which has breaking changes which affect this project. The short term fix might be to lock the package version of `swift-parsing` to `0.11.0` as it automatically pulls the breaking change currently. I'd be happy to look at adding support for Swift 5.8 as well.

Thanks!

**Comment by JaapWijnen** [comment]
Hey! Fun to hear that you're using my project! I'd love to update it for you. Can't promise a timeline so if you need it asap I'd recommend making a PR I'm definitely open to accepting it! 
Was wondering would you have any improvements you'd like to see since you've been using the library?
